### ISSUE TITLE
Blog list on Home

### ISSUE THREAD

**Issue by tedmagaoay** [zwbetz-gh/uswds-hugo-theme#1]
I want to show all the posts on Home instead of _index.md contents so that whenever website loads it will show all the blog posts. How would I do that?

**Comment by zwbetz-gh** [comment]
Hi there. I seem to have missed your issue. I've since updated the readme to clarify my stance on things, but in a nutshell, since this theme is built specifically for my site, I will not accept issues or pull requests from others. Thanks. 

Also see https://github.com/zwbetz-gh/uswds-hugo-theme/commit/8b4d7702566b02d6d7f4f26da4ab55350ce63332
